appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: daNexDH5SBZSphDHBsZKcUXPocx+nMk8XQ3ExkMgUJU8XI40LbbK6BNdxEFJFWDacojTp6t1gdZrCjxh6eoCLcaQOhOlSM8OX2GjH0sEJ6imPBRq8pQhCIgaJTlRbFedIq/G6PM0YEac7q6UtfPQz/4VXRfizbkOPwICg0fzGrhAL57T0khiXhvT/RtfS+IsunaoMSMTYdqUzIVj2mtAURuBNYigBYt1VdByF5uW87dJMuT3rlG3WD7q0bjBT5g4EliOsIRSDVdyHY4wVd7dVC0EkPGM0C04VJJbHtcrpE+T7E7r5g9DKmK66kYpF68sLNZtOl6oPlDJGEblSokdTPC8owifa7g2HmLv8Kcb3lQyENXSzPBG4XEUUlcCNGCcFc5qMvfagHLI0z/EfHj4m1moF7J6WLuBOIDqJkrFvlCv91CYrfw2wcPG2riYWdc08hR5KbWA2PTJZ0JRmpxM9QXQS8Nq66ND1ib9N2A05NTkgy1PbqrBZhVG0LrvYd6+pZp18iwHJQ8FSEtZQfn5XRdS8lNt6cZd2XPvAzD/hd6TRlwmv4IFcHiijrMFfdcnv/T1RpegpupGY4pDg/LS72TlpbJDx1nhLpl20m6N8Bk4UVzbW7j1gnd8eWtGf8NpYXnqXxJYIZWEnvq5kCP3X84F+yGfDC1sq9sD/ynV1Eg=}
